# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20180929_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
