# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='greetings',
            field=models.IntegerField(default=0),
        ),
    ]
