# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile_greetings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileGreetedByActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greetedgreeter', to='rango.UserProfile')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greetedliker', to='rango.UserProfile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLikedByActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedgreeter', to='rango.UserProfile')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedliker', to='rango.UserProfile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile')),
            ],
        ),
    ]
