# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20181002_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilegreetedbyactiveuser',
            name='greeter',
        ),
    ]
