# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_remove_profilegreetedbyactiveuser_greeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilegreetedbyactiveuser',
            name='greeter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='greeter', to='rango.UserProfile'),
        ),
        migrations.AlterField(
            model_name='profilegreetedbyactiveuser',
            name='profile',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profilegreetedbyactiveuser',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='profilelikedbyactiveuser',
            name='profile',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profilelikedbyactiveuser',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
